name: Validar Proyecto

on:
  pull_request:

jobs:
  estructura:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Verificar CSS
        run: test -f css/style.css

      - name: Verificar JavaScript
        run: test -f js/script.js
