name: Validar Proyecto

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  estructura:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Verificar CSS
        run: test -f css/styles.css

      - name: Verificar JavaScript
        run: test -f js/script.js
